[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
description = "Rust bindings for the VTE 3 library"
license = "MIT"
name = "vte-rs"
version = "0.2.0"

[dependencies]
bitflags = "1"
gdk-sys = "0.8"
gdk = "0.10"
gio-sys = "0.8"
gio = "0.6"
glib = "0.7"
glib-sys = "0.8"
gobject-sys = "0.8"
gtk = "0.6"
gtk-sys = "0.8"
libc = "0.2"
pango = "0.6"
vte-sys = { version="0.2.1", path="./vte-sys-rs"}

[lib]
name = "vte"

[features]
v0_40 = ["vte-sys/v0_40"]
v0_42 = ["v0_40", "vte-sys/v0_42"]
v0_44 = ["v0_42", "vte-sys/v0_44"]
v0_46 = ["v0_44", "vte-sys/v0_46"]
v0_48 = ["v0_46", "vte-sys/v0_48"]
